/* Generated By:JavaCC: Do not edit this line. TabParserConstants.java */
package se.modlab.generics.sstruct.tables;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TabParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int LINEFEED = 7;
  /** RegularExpression Id. */
  int DELIMITER = 8;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 9;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 10;
  /** RegularExpression Id. */
  int HEX_LITERAL = 11;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 12;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL_CORRECT = 13;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL_MICROSOFT = 14;
  /** RegularExpression Id. */
  int EXPONENT = 15;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 16;
  /** RegularExpression Id. */
  int STRING_LITERAL = 17;
  /** RegularExpression Id. */
  int DATETIME_LITERAL_CORRECT = 18;
  /** RegularExpression Id. */
  int DATETIME_LITERAL_MICROSOFT = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "<TRUE>",
    "<FALSE>",
    "\"\\n\"",
    "<DELIMITER>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL_CORRECT>",
    "<FLOATING_POINT_LITERAL_MICROSOFT>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<DATETIME_LITERAL_CORRECT>",
    "<DATETIME_LITERAL_MICROSOFT>",
  };

}
